name = "referee-fyi-share"
compatibility_date = "2023-12-18"
main = "./src/index.ts"

kv_namespaces = [
    { binding = "SHARES", id = "667b3f219f284aa7b4a88d37044ae9d9" },
    { binding = "INVITATIONS", id = "bf2c971507354390ba314b8e18b4e908" },
    { binding = "USERS", id = "bf2c971507354390ba314b8e18b4e908" }
]

[build]
command = "npm install && npm run build"

[[durable_objects.bindings]]
name = "INCIDENTS"
class_name = "EventIncidents"

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]

[[migrations]]
tag = "v1"
new_classes = ["EventIncidents"]